include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - build/**
    - android/**
    - windows/**
    - linux/**
    - macos/**

linter:
  rules:
    avoid_print: true
